[package]
name = "dark-remote-common"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }

[lints]
workspace = true
